sudo: required
language: generic

services:
  - docker

env:
  global:
    - TRAVIS_DEBIAN_EXTRA_REPOSITORY="http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
    - TRAVIS_DEBIAN_LINTIAN=false
    - TRAVIS_DEBIAN_BACKPORTS=xenial-security
    - TRAVIS_DEBIAN_SECURITY_UPDATES=true
    - TRAVIS_DEBIAN_EXTRA_REPOSITORY_GPG_URL="https://raw.githubusercontent.com/OneSignal/capnproto-debian/master/ubuntu-toolchain-r.pub"
  matrix:
    - TRAVIS_DEBIAN_DERIVATIVE=ubuntu TRAVIS_DEBIAN_DISTRIBUTION=xenial


script:
  - wget -O- http://travis.debian.net/script.sh | sh -

